# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2023-present Peter Tuschy (foss@bofh42.de)

# this is the used by borgbackup-server.sh (not sourced)

# destination host(s) for backup
# use fqdn and not IP (for now)
# like BB_DEST_1=borg.yourdomain.de
# or use --server on the command line
# or -[2-9] and defined BB_DEST_[2-9]
# for now BB_DEST_[1-9], BORG_REPO_[1-9], BB_CREATE_[1-9] is supported
# and     BB_PRUNE_HOURLY, BB_PRUNE_DAILY, BB_PRUNE_WEEKLY, BB_PRUNE_MONTHLY, BB_PRUNE_YEARLY

BB_DEST_1=

# optional define different parameter then the script does by defautl, but you need to give -1 on the command line
#BB_CREATE_1=" --error --exclude-if-present .nobackup --exclude-if-present .bbe --keep-exclude-tags --exclude-caches --exclude-nodump $(ver_ge $BB_VER $BB_VER12 || echo "--noatime")"
#BB_PRUNE_HOURLY_1=13
#BB_PRUNE_DAILY_1=8
#BB_PRUNE_WEEKLY_1=6
#BB_PRUNE_MONTHLY_1=18
#BB_PRUNE_YEARLY_1=3
# you can set every borg supported repo
# ssh is default and looks like this
#BORG_REPO_1=ssh://zborg@${BB_DEST_1%%.*}/~/hosts/${HOSTNAME%%.*}


# 1 is default for BB_DEST
# for 2-9 you need a extra call of borgbackup-server.sh -[2-9]
BB_DEST_2=
BB_DEST_3=
BB_DEST_4=
BB_DEST_5=
BB_DEST_6=
BB_DEST_7=
BB_DEST_8=
BB_DEST_9=
